### ISSUE TITLE
App’s stuck and dragging Electron app over causes JS error

### ISSUE THREAD

**Issue by gryzzly** [bytedance/debugtron#3] opened 2019-11-20 12:37 UTC
The app is stuck with the spinner.

Dragging the installed app over causes JS error:

<img width="1440" alt="Screenshot 2019-11-20 at 19 35 14" src="https://user-images.githubusercontent.com/26131/69239536-077c2880-0bcd-11ea-89fc-bb60ffff60be.png">

Using Macbook Pro with macOS 10.14.6 (18G103). 

Debugtron version 0.4.0. 

Let me know if I can help debugging this or I am doing something wrong.

**Comment by pd4d10** [comment] 2019-11-23 04:31
Hi @gryzzly, thanks for your report!

Probably there are two issues:

1. The stuck is caused by Electron apps detection step. It looks like some errors are not handled correctly in detection step. Could you please provide a screenshot of your apps' list?
2. DnD errors also not be handled correctly. Could you please provide the app your are trying to drop? The name of it would be enough if it can be publicly downloaded.

If the above information relates to your privacy, it doesn't matter if you don't post it here :)

**Comment by pd4d10** [comment] 2019-11-23 04:41
For macOS, the Electron app detection implementation is in this file:

https://github.com/bytedance/debugtron/blob/998a9ced2ee86e18a57a5bdf8b43aa5ece8fc77d/src/main/macos.ts#L14

Discussions and PRs are very welcome if you want to debug it yourself.

**Comment by imyzf** [comment] 2019-11-27 11:02
![image](https://user-images.githubusercontent.com/8298849/69717960-140dfd00-1148-11ea-8d36-1affed320076.png)

+1，only available when I opened at first time. When I open it again, it is stuck with the spinner.

Using mac mini with macOS 10.14.6 (18G1012).
Debugtron version 0.4.0.

**Comment by pd4d10** [comment] 2019-12-02 02:47
Hi, @gryzzly @imyzf , we have likely found the reason causing this issue, which probably has been fixed in the latest [v0.4.1](https://github.com/bytedance/debugtron/releases). Please give it a try.

**Comment by imyzf** [comment] 2019-12-02 11:29
The error is disappeared, but the spinner existed. Need I clean any storage file before update?

**Comment by pd4d10** [comment] 2019-12-03 02:19
@imyzf OK, thank for the feedback. Seems it has a problem with Electron apps detection step.

**Comment by imyzf** [comment] 2019-12-04 09:52
> is the drag feature working as expected?

No, it does nothing.

**Comment by pd4d10** [comment] 2019-12-24 04:49
Hi, @imyzf @gryzzly , this issue is probably related to https://github.com/bytedance/debugtron/pull/4.

[v0.4.2](https://github.com/bytedance/debugtron/releases) has been released to fix this.

**Comment by imyzf** [comment] 2019-12-24 11:52
Great! It works!

**Comment by pd4d10** [comment] 2020-01-15 16:10
Hi, I'm going to close this. Feel free to reopen it

**Closed by pd4d10** 2020-01-15 16:10 UTC
